[gcp_service_account]
# ... (Cole aqui as suas chaves do Google Cloud que já temos) ...

senha_app = "Cobli@1609"
url_planilha = "https://docs.google.com/spreadsheets/d/1PfVphTdLemyoRpUmHHXubd8vGIWn9RfDcVVWezgi6WI/edit?gid=1282904093#gid=1282904093"
